name: CI/CD whe pull-request or merge to main branch

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Install dependencies
        run: |
          export PATH=$HOME/go/bin:$(go env GOPATH)/bin:/go/bin:$PATH
          go mod download
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
          go get github.com/onsi/gomega/...

      - name: Test with the Go CLI
        run: ginkgo -r
          
