name: CI/CD whe pull-request or merge to main branch

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Test with the Go CLI
        run: ginkgo -r
          
